# organization name, it's used to get github repo url, also in page title
name: thenables

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       thenables
description: Promise-based JavaScript Modules
keywords:    Promises

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - pswd
 - slave
 - bcrypt-then
 - requisition
 - exit-then
 - timeout-then
 - lazy-then

# list of maintainers, this won't be sorted
maintainers:
 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
